### ISSUE TITLE
Multilingual Translation Error for Kannada (kn), Malayalam (ml), Telugu (te), and Tamil (ta) Locales

### ISSUE THREAD

**Issue by tejaswini-dev-techie** [leancodepl/arb_translate#5] opened 2024-02-23 13:04 UTC
Version
**arb_translate: 0.0.1**

<img width="914" alt="Screenshot 2024-02-23 at 7 03 43 PM" src="https://github.com/leancodepl/arb_translate/assets/79466038/fd9b745e-3332-476b-8c62-f9cc5d804573">

**Comment by RobertOdrowaz** [comment] 2024-02-25 10:54
Hi, seems like the issue is caused by the model itself. Gemini doesn't want to generate content in those languages. Hopefully, Google will fix this soon. We are also planning on adding support for other model providers which may work better in this case. I will close this issue because there is nothing I can actually do.
<img width="828" alt="image" src="https://github.com/leancodepl/arb_translate/assets/9675199/d79d0f73-0349-4cb5-90ec-ce718cba691f">

**Closed by RobertOdrowaz** 2024-02-25 10:54 UTC

**Comment by pasaneramusugoda** [comment] 2024-05-25 04:44
I found the URL below, which shows what languages they support as of now. Do you have any references for upcoming languages?

https://ai.google.dev/gemini-api/docs/models/gemini#available-languages
